import test from 'node:test';
import assert from 'node:assert/strict';
import {newPlayer,applyAction,publicView} from '../supabase/functions/dorath-p1/engine.js';
import {master} from '../supabase/functions/dorath-p1/master-data.js';
const play=(g,p,type,other={})=>applyAction(g,p,{type,...other});
function game(){const a=newPlayer('Ana','ABC123',''),b=newPlayer('Beto','ABC123','');return {id:crypto.randomUUID(),motherCode:'XYZ123',hostPlayerId:a.id,rooms:[{code:'ABC123',name:'Sala 1',team:''}],players:[a,b],phase:'lobby',round:1,turnIndex:0,globalStates:{},violence:0,marcos:{},arkOpened:false,preparationClosed:false,rupturesResolved:{},pendingRupture:null,activeThreats:[],seenThreats:[],lastSpawnRound:0,trades:[],history:[],revision:0,pendingConsequencePlayers:[],pendingThreat:null,marcoQueue:[],finalScores:null}}
function start(g){for(const p of g.players)play(g,p,'setup',{rolls:[2,4,6],order:['conhecimento','influencia','provisoes']});play(g,g.players[0],'start')}
test('master v1.5 preserva 54 códigos e reorganiza a Zona 1',()=>{
 const names=master.houses.slice(0,8).map(h=>h.name);
 assert.deepEqual(names,['Criação de Adão','Jeová prepara o Jardim do Éden','Adão é colocado no jardim','As duas árvores','Cultivar e cuidar do jardim','O Mandamento no Jardim','Vida e tarefas no jardim','Adão dá nome aos animais']);
 assert.equal(master.masterVersion,'P1-MASTER-v1.5');
 assert.equal(master.houses.length,54);
 assert.equal(master.houses[3].classification,'Casa dinâmica / Escolha');
 assert.equal(master.houses[3].family,'Recurso / oportunidade');
 assert.equal(master.houses[4].family,'Interação positiva');
 assert.equal(master.houses[6].family,'Preparação para Marco');
 assert.equal(master.qr.readByApp,false);
});
test('Casa 04 apresenta as árvores sem ativar MANDAMENTO nem antecipar a Queda',()=>{const g=game();start(g);const [a]=g.players;a.house=3;play(g,a,'move',{roll:1});assert.equal(a.house,4);assert.equal(g.phase,'active');assert.equal(!!g.globalStates.MANDAMENTO,false);assert.equal(g.pendingRupture,null)});
test('Casa 06 ativa MANDAMENTO e a Casa 07 permite resolver escolhas das árvores',()=>{const g=game();start(g);const [a]=g.players;a.house=5;play(g,a,'move',{roll:1});assert.equal(g.phase,'marco-roll');play(g,a,'marcoD4',{d4:2});assert.equal(g.phase,'marco-individual');play(g,a,'marcoIndividualD4',{d4:1});assert.equal(g.globalStates.MANDAMENTO,true);a.house=7;const before=a.resources.provisoes;play(g,a,'specialChoice',{card:'vida',option:'provisoes'});assert.equal(a.resources.provisoes,before+2)});
test('correção manual usa número da casa e registra histórico sem QR',()=>{const g=game();start(g);const [a]=g.players;a.house=3;play(g,a,'correctPosition',{house:4,reason:'ajuste de mesa'});assert.equal(a.house,4);assert.match(g.history.at(-1).message,/P1-040/)});

test('setup, Marco collective and separate individual D4',()=>{const g=game();start(g);const [a,b]=g.players;a.house=5;play(g,a,'move',{roll:1});assert.equal(g.phase,'marco-roll');play(g,a,'marcoD4',{d4:2});assert.equal(g.phase,'marco-individual');play(g,a,'marcoIndividualD4',{d4:3});assert.equal(g.phase,'active');assert.equal(a.resources.conhecimento,3);assert.equal(b.resources.conhecimento,2);assert.equal(g.marcos[6].d4,2)});
test('later player landing on an already active Marco gets individual D4 once',()=>{const g=game();start(g);const [a,b]=g.players;g.marcos[10]={d4:2};a.house=9;play(g,a,'move',{roll:1});assert.equal(g.phase,'marco-individual');play(g,a,'marcoIndividualD4',{d4:2});assert.equal(a.resources.influencia,4);assert.equal(g.phase,'active');play(g,a,'endTurn');b.house=9;play(g,b,'move',{roll:1});assert.equal(g.phase,'marco-individual');play(g,b,'marcoIndividualD4',{d4:1});assert.equal(b.resources.influencia,4)});
test('collective Rupture stops excess movement and synchronizes after preparation',()=>{const g=game();start(g);const [a,b]=g.players;a.house=11;play(g,a,'move',{roll:6});assert.equal(a.house,12);assert.equal(g.phase,'rupture-prep');play(g,b,'prepare',{option:'pass'});assert.equal(g.phase,'rupture-roll');play(g,a,'ruptureD4',{d4:2});assert.deepEqual(g.players.map(p=>p.house),[13,13]);assert.equal(g.rupturesResolved.R12.d4,2)});
test('physical Consequence cycle applies card-specific D4',()=>{const g=game();start(g);const [a]=g.players;a.house=13;play(g,a,'move',{roll:1});assert.equal(g.phase,'consequence-draw');play(g,a,'consequence',{card:'CNS-P1-03',d4:4});assert.equal(a.resources.conhecimento,0);assert.equal(a.resources.influencia,2);assert.equal(g.phase,'active')});
test('Nefilim first entry and P1-390 do not spawn a second threat',()=>{const g=game();start(g);const [a,b]=g.players;a.house=37;g.marcos[37]={d4:2};play(g,a,'move',{roll:1});assert.equal(g.phase,'threat-spawn');g.pendingThreat.card='opressor';play(g,a,'threatSpawnD4',{d4:2});assert.equal(g.activeThreats.length,1);a.house=38;g.phase='active';a.lastMovedRound=0;play(g,a,'move',{roll:1});assert.equal(g.phase,'rupture-prep');play(g,b,'prepare',{option:'pass'});play(g,a,'ruptureD4',{d4:3});assert.equal(g.seenThreats.length,1);assert.equal(g.activeThreats[0].aggravated,true)});
test('Dominador uses D8 decider then D4 tier with no extra reward roll',()=>{const g=game();start(g);const [a]=g.players;a.house=38;a.resources.influencia=6;const id=crypto.randomUUID();g.activeThreats=[{id,card:'dominador',successes:2,aggravated:false}];play(g,a,'threatAttempt',{threatId:id,attribute:'influencia',roll:1});assert.equal(g.phase,'dominator-decider');play(g,a,'dominatorD8',{roll:8});assert.equal(g.phase,'dominator-tier');play(g,a,'dominatorTierD4',{d4:2});assert.equal(g.dominator.options.length,3);play(g,a,'dominatorChoice',{option:0});assert.equal(g.phase,'active');assert.equal(g.activeThreats.length,0)});
test('secret mission cycle draws all sixteen before repeating',()=>{let ids=[];for(let i=0;i<16;i++){const p=newPlayer('A','ABC123','',ids);assert.ok(!ids.includes(p.secretMissionId));ids.push(p.secretMissionId)}const q=newPlayer('B','ABC123','',ids);assert.notEqual(q.secretMissionId,ids.at(-1))});
test('Arca closes at P1-500, stores secret D6, then guided final reaches P1-540',()=>{const g=game();start(g);const [a,b]=g.players;g.arkOpened=true;a.house=b.house=49;a.resources.provisoes=b.resources.provisoes=5;play(g,a,'move',{roll:6});assert.equal(a.house,50);play(g,a,'arkFinalize',{enter:true,characterId:'adao'});play(g,a,'endTurn');play(g,b,'move',{roll:2});play(g,b,'arkFinalize',{enter:false});assert.equal(g.preparationClosed,true);play(g,a,'preservationD6',{roll:4});play(g,a,'advanceFinal');assert.deepEqual(g.players.map(p=>p.house),[51,51]);play(g,a,'advanceFinal');assert.equal(g.phase,'rupture-roll');play(g,a,'ruptureD4',{d4:4});assert.deepEqual(g.players.map(p=>p.house),[53,53]);play(g,a,'advanceFinal');assert.equal(g.phase,'ended');assert.equal(g.finalScores.length,1);assert.equal(g.finalScores[0].id,a.id);assert.equal(publicView(g,b).me.preserved,false)});
